#+TITLE: Plankton Imager Edge-AI

* Introduction

This directory contains the Python code for the Plankton Imager Edge
AI system, sponsored by the Turing Institute.



Features include

- UDP listener that receives images from the PI10 instrument.

- Two classifiers - a ResNet50 and a ResNet18 that can discriminate
  copepod, non-copepod and detritus.

- Ability to store images in bin files (faster than writing individual
  images).

- Sending of summary data to Azure storage for use by a digital
  dashboard.

- Display of labelled images

- Parsing of GPS data

- Extraction of morphological measurements





* Installation: Linux

** Install Python environment, this has been tested on 3.8.10 (linux) and 3.11.0 (windows)

Linux tested using this version of python:
wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz


To install required packages. Linux:

#+begin_src bash
  cd ~/git/rapid-plankton/edge-ai
  python3 -m venv env
  source env/bin/activate
  python3 -m pip install --upgrade pip
  python3 -m pip install -r requirements-jetson.txt
  
  It is likely at this point that you get an error, as the version of jetpack you are using has a specific version of torch in the requirements-jetson.txt, I would suggest we move towards using jetson containers for the correct version https://github.com/dusty-nv/jetson-containers/tree/master
  
  A possibly unrelated error after updating the jetson... you may also have to sudo apt install libopenblas-dev -y
  
#+end_src

If using azure command line interface tools (easy to install on jetson):

#+begin_src bash
  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#+end_src


To activate in Linux:

Subsequent activation (required every time). Linux:

#+begin_src bash
  cd ~/git/rapid-plankton/edge-ai
  source env/bin/activate
#+end_src


Once in (env), on Linux test with:

#+begin_src bash
  ./edge-ai.py --help
  ./classifier.py --folder ../data/examples --output /home/joe/Downloads/classifications.csv -m 2 -b 100
  ./extractor.py --folder ../data/examples --output /home/joe/Downloads/sizes.csv
  ./gps.py --folder ../data/examples --output /home/joe/Downloads/gps.csv
  python 
  import torch
  torch.cuda.is_available()
#+end_src



* Installation: Windows

** Install Python environment, tested on python 3.11.0 for windows

Install python 3.11.0 as tested on my Windows PC using MINGW64 bash on VS:
wget https://www.python.org/ftp/python/3.11.0/python-3.11.0.exe

Install dependencies on Windows:

#+begin_src bash
  cd ~/git/rapid-plankton/edge-ai
  python -m venv env
  source env/scripts/activate
  python -m pip install --upgrade pip
  python -m pip install -r requirements.txt
  pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
#+end_src

To activate in Windows:

#+begin_src bash
  cd ~/git/rapid-plankton/edge-ai
  env/scripts/activate
#+end_src

Once in (env), on Windows test on the command line with:

#+begin_src bash
  python edge-ai.py --help
  python classifier.py --folder ../data/examples --output C:/Users/JR13/Downloads/classifications.csv -m 2 -b 100
  python extractor.py --folder ../data/examples --output C:/Users/JR13/Downloads/sizes.csv
  python gps.py --folder ../data/examples --output C:/Users/JR13/Downloads/gps.csv
  python 
  import torch
  torch.cuda.is_available()
#+end_src








* Usage
** Help

Features are switched on or off and configured by means of command
line arguments. For more informations see:

#+begin_src bash
  ./edge-ai.py --help
#+end_src

If you want to see progress, then use =--verbose= to log to the
terminal.

If things are going badly and you need more debug information, then
set =--loglevel DEBUG=.

Verbose diagnostics for the dashboard sending path are enabled when
=--verbose=, =--debug=, or =--loglevel DEBUG= is used.  These entries
are prefixed with =[send-diagnostics]= in the logs.

In general, the more things you switch on, the lower the throughput.

Stopping the app is currently bug - try pressing =q=. If that doesn't
work, type =CTRL-C=.



* Here are some typical use cases

** Fast storage of images

Plug in your external hard drive and change directory to where you
want to store your data. Run this command:

#+begin_src
  ./edge-ai.py --store
#+end_src

Images are stored in =bin= files. these can be split up later into
tiff file using the supplied =split_bin.py= script.

** Local classification

Run the classifier. Use background correction.

#+begin_src
  ./edge-ai.py --classify --verbose  --background-correction
#+end_src

Counts of copepod, non-copepod and detritus per minute are logged to a file.
